export const mockProperties = [
  {
    id: 1,
    slug: "penthouse-torre-azul-colon",
    title: "Penthouse en Torre Azul",
    subtitle: "Vistas panorámicas · 4 ambientes · 210 m²",
    address: "Av. Colón 2500, piso 22",
    neighborhood: "Centro",
    city: "Mar del Plata",
    price: 320000,
    currency: "USD",
    expenses: 85000,
    expensesCurrency: "ARS",
    operation: "venta",
    type: "departamento",
    status: "disponible",   // disponible | reservado | vendido
    featured: true,
    isNew: true,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 3,
    garage: 2,
    surfaceCovered: 185,
    surfaceTotal: 210,
    surfaceTerrace: 45,
    floor: 22,
    totalFloors: 24,
    orientation: "NO",
    antiquity: 2,
    description: `Excepcional penthouse en el emblemático edificio Torre Azul, con vistas panorámicas al mar y a la ciudad desde todos sus ambientes. Terminaciones de primer nivel, pisos de porcelanato premium y aberturas con doble vidrio hermético.\n\nLa distribución inteligente incluye living-comedor de doble altura, cocina integrada con isla, tres dormitorios en suite y una impresionante terraza privada con jacuzzi.\n\nComodidades del edificio incluyen piscina climatizada, gimnasio equipado, salón de usos múltiples y seguridad 24hs. Cochera doble en subsuelo incluida en el precio.`,
    highlights: ["Vista panorámica al mar", "Terraza privada con jacuzzi", "Cocina con isla", "Piso 22 con vistas 360°"],
    amenities: ["Pileta climatizada", "Gimnasio", "SUM", "Seguridad 24hs", "Cochera doble", "Portería", "Ascensor"],
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=85",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=85",
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=1200&q=85",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=85",
    ],
    agent: { name: "Valentina Cruz", phone: "+54 223 600-0001", photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
    videoUrl: null,
    virtualTourUrl: null,
    lat: -38.0046, lng: -57.5423,
  },
  {
    id: 2,
    slug: "casa-moderna-acantilados",
    title: "Casa moderna con pileta",
    subtitle: "Diseño contemporáneo · 5 ambientes · 450 m²",
    address: "Calle Las Gaviotas 342",
    neighborhood: "Los Acantilados",
    city: "Mar del Plata",
    price: 480000,
    currency: "USD",
    expenses: null,
    operation: "venta",
    type: "casa",
    status: "disponible",
    featured: true,
    isNew: false,
    rooms: 5,
    bedrooms: 4,
    bathrooms: 3,
    garage: 2,
    surfaceCovered: 320,
    surfaceTotal: 2500,
    surfaceTerrace: null,
    floor: null,
    orientation: "S",
    antiquity: 5,
    description: `Casa de diseño contemporáneo ubicada en un lote de 2.500 m² en el exclusivo barrio de Los Acantilados, a metros del mar. La propiedad fue concebida por el estudio de arquitectura Mazzoni & Asociados con un enfoque en la integración entre espacios interiores y exteriores.\n\nLa planta baja cuenta con living de doble altura, comedor formal e informal, cocina gourmet abierta y lavadero. El sector de servicio es completamente independiente. En el primer piso se encuentran los cuatro dormitorios, todos en suite con placard a medida.`,
    highlights: ["Lote de 2.500 m²", "Pileta desbordante", "Quincho con parrilla", "Diseño premiado"],
    amenities: ["Pileta", "Quincho", "Parrilla", "Jardín", "Garage doble", "Alarma", "Riego automático"],
    photos: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=85",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=85",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200&q=85",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=85",
    ],
    agent: { name: "Rodrigo Salinas", phone: "+54 223 600-0002", photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" },
    lat: -38.0820, lng: -57.5190,
  },
  {
    id: 3,
    slug: "departamento-centro-rivadavia",
    title: "Departamento luminoso",
    subtitle: "Pleno centro · 2 ambientes · 72 m²",
    address: "Rivadavia 2100, piso 8 A",
    neighborhood: "Centro",
    city: "Mar del Plata",
    price: 2100,
    currency: "USD",
    expenses: 55000,
    expensesCurrency: "ARS",
    operation: "alquiler",
    type: "departamento",
    status: "disponible",
    featured: false,
    isNew: true,
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    garage: 1,
    surfaceCovered: 68,
    surfaceTotal: 72,
    surfaceTerrace: null,
    floor: 8,
    orientation: "NE",
    antiquity: 8,
    description: `Luminoso departamento de dos ambientes en el corazón de Mar del Plata, a una cuadra de la peatonal. Octavo piso con vistas despejadas a la ciudad y excelente asoleamiento.\n\nRecientemente renovado con materiales de calidad: pisos de madera flotante, cocina con muebles a medida y baño con ducha lluvia. Equipado con split frío/calor. Cochera opcional en el mismo edificio.`,
    highlights: ["Vistas despejadas", "Renovado 2023", "Piso 8", "A estrenar"],
    amenities: ["Ascensor", "Portería", "Cochera opcional", "Laundry"],
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=85",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=85",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=85",
    ],
    agent: { name: "Valentina Cruz", phone: "+54 223 600-0001", photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
    lat: -37.9990, lng: -57.5490,
  },
  {
    id: 4,
    slug: "chalet-sierra-de-los-padres",
    title: "Chalet en Sierra de los Padres",
    subtitle: "Lago propio · 4 ambientes · 2500 m² lote",
    address: "Camino del Lago 124",
    neighborhood: "Sierra de los Padres",
    city: "Mar del Plata",
    price: 210000,
    currency: "USD",
    expenses: null,
    operation: "venta",
    type: "casa",
    status: "reservado",
    featured: true,
    isNew: false,
    rooms: 4,
    bedrooms: 3,
    bathrooms: 2,
    garage: 1,
    surfaceCovered: 190,
    surfaceTotal: 2500,
    antiquity: 12,
    description: `Chalet ubicado en un lote de 2.500 m² con acceso directo a lago privado en la serrana de los Padres, a 20 minutos del centro de Mar del Plata. La propiedad combina la comodidad del diseño moderno con la calidez de los materiales naturales: piedra, madera de quebracho y grandes ventanales que enmarcan el paisaje.`,
    highlights: ["Lago propio con muelle", "Entorno natural único", "20 min del centro", "Diseño en piedra y madera"],
    amenities: ["Muelle privado", "Fogón exterior", "Jardín arbolado", "Estacionamiento"],
    photos: [
      "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=1200&q=85",
      "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=85",
      "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=1200&q=85",
    ],
    agent: { name: "Marcela Torres", phone: "+54 223 600-0003", photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80" },
    lat: -38.0480, lng: -57.7200,
  },
  {
    id: 5,
    slug: "oficina-premium-luro",
    title: "Oficina piso completo",
    subtitle: "Edificio Premium · 280 m² · 3 cocheras",
    address: "Av. Luro 3500, piso 12",
    neighborhood: "Centro",
    city: "Mar del Plata",
    price: 4500,
    currency: "USD",
    expenses: 180000,
    expensesCurrency: "ARS",
    operation: "alquiler",
    type: "oficina",
    status: "disponible",
    featured: false,
    isNew: false,
    rooms: 8,
    bedrooms: null,
    bathrooms: 3,
    garage: 3,
    surfaceCovered: 280,
    surfaceTotal: 280,
    floor: 12,
    orientation: "NO",
    antiquity: 3,
    description: `Piso completo en uno de los edificios corporativos más modernos de la ciudad. Planta libre adaptable a cualquier necesidad, con sala de reuniones vidriada, kitchenette equipada y tres sanitarios. Vistas panorámicas al mar desde los tres frentes del edificio. Ideal para estudios profesionales, consultoras o empresas en expansión.`,
    highlights: ["Piso completo 280 m²", "3 cocheras incluidas", "Vista al mar", "LEED certificado"],
    amenities: ["Generador propio", "Datacenter", "Control de acceso", "Aire central", "3 ascensores"],
    photos: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=85",
      "https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=1200&q=85",
    ],
    agent: { name: "Rodrigo Salinas", phone: "+54 223 600-0002", photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80" },
    lat: -37.9960, lng: -57.5530,
  },
  {
    id: 6,
    slug: "duplex-guemes-moderno",
    title: "Dúplex moderno en Güemes",
    subtitle: "Barrio trendy · 3 ambientes · A estrenar",
    address: "Güemes 3240",
    neighborhood: "Güemes",
    city: "Mar del Plata",
    price: 145000,
    currency: "USD",
    expenses: 40000,
    expensesCurrency: "ARS",
    operation: "venta",
    type: "departamento",
    status: "disponible",
    featured: false,
    isNew: true,
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    surfaceCovered: 110,
    surfaceTotal: 118,
    surfaceTerrace: 18,
    floor: 3,
    orientation: "E",
    antiquity: 0,
    description: `Dúplex a estrenar en el corazón del barrio Güemes, el polo gastronómico y cultural de Mar del Plata. Terminaciones de primer nivel con porcelanato rectificado, cocina abierta con muebles italianos y baños revestidos en microcemento. Terraza privada con asador incorporado.`,
    highlights: ["A estrenar", "Barrio Güemes", "Terraza con asador", "Cochera incluida"],
    amenities: ["Cochera", "Baulera", "Ascensor", "Seguridad"],
    photos: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1200&q=85",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=85",
    ],
    agent: { name: "Valentina Cruz", phone: "+54 223 600-0001", photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
    lat: -37.9980, lng: -57.5630,
  },
  {
    id: 7,
    slug: "local-comercial-san-martin",
    title: "Local a la calle — peatonal",
    subtitle: "Esquina comercial · 180 m² · Alto tráfico",
    address: "San Martín y Rivadavia — esquina",
    neighborhood: "Microcentro",
    city: "Mar del Plata",
    price: 3800,
    currency: "USD",
    expenses: 90000,
    expensesCurrency: "ARS",
    operation: "alquiler",
    type: "local",
    status: "disponible",
    featured: false,
    isNew: false,
    rooms: 1,
    bedrooms: null,
    bathrooms: 2,
    garage: null,
    surfaceCovered: 180,
    surfaceTotal: 180,
    floor: 0,
    antiquity: 20,
    description: `Local comercial en esquina sobre peatonal San Martín, una de las arterias de mayor tráfico peatonal de la ciudad. El espacio es de planta libre con excelente ventilación e iluminación natural. Dos frentes vidriados de piso a techo, depósito trasero y dos sanitarios. Ideal para retail, gastronomía o showroom.`,
    highlights: ["Esquina en peatonal", "2 frentes vidriados", "180 m² planta libre", "Depósito incluido"],
    amenities: ["Depósito trasero", "2 sanitarios", "Acceso discapacitados"],
    photos: [
      "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200&q=85",
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=85",
    ],
    agent: { name: "Marcela Torres", phone: "+54 223 600-0003", photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80" },
    lat: -37.9997, lng: -57.5501,
  },
  {
    id: 8,
    slug: "monoambiente-inversion-güemes",
    title: "Monoambiente inversión",
    subtitle: "Rentabilidad garantizada · Güemes · 38 m²",
    address: "Matheu 2800",
    neighborhood: "Güemes",
    city: "Mar del Plata",
    price: 75000,
    currency: "USD",
    expenses: 25000,
    expensesCurrency: "ARS",
    operation: "venta",
    type: "departamento",
    status: "disponible",
    featured: false,
    isNew: true,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    garage: null,
    surfaceCovered: 36,
    surfaceTotal: 38,
    floor: 5,
    orientation: "N",
    antiquity: 1,
    description: `Moderno monoambiente a estrenar en edificio boutique de Güemes, ideal para inversión con alta rentabilidad. El proyecto ya cuenta con inquilino precalificado. Terminaciones premium, amenities completos y gestión del alquiler incluida por 12 meses sin cargo adicional.`,
    highlights: ["Rentabilidad 6% anual", "Gestión de alquiler incluida", "A estrenar", "Amenities completos"],
    amenities: ["Rooftop", "Cowork", "Bici-estacionamiento", "Smart lock"],
    photos: [
      "https://images.unsplash.com/photo-1560185008-a33f5f0a5935?w=1200&q=85",
    ],
    agent: { name: "Valentina Cruz", phone: "+54 223 600-0001", photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80" },
    lat: -37.9985, lng: -57.5640,
  },
  {
    id: 9,
    slug: "terreno-playa-grande",
    title: "Terreno en Playa Grande",
    subtitle: "Frente al mar · 800 m² · Única oportunidad",
    address: "Costanera Sur s/n",
    neighborhood: "Playa Grande",
    city: "Mar del Plata",
    price: 550000,
    currency: "USD",
    expenses: null,
    operation: "venta",
    type: "terreno",
    status: "disponible",
    featured: true,
    isNew: false,
    rooms: null,
    bedrooms: null,
    bathrooms: null,
    garage: null,
    surfaceCovered: null,
    surfaceTotal: 800,
    antiquity: null,
    description: `Terreno de 800 m² con frente al mar en la exclusiva zona de Playa Grande. Zoning residencial de alta densidad que permite construir edificio de hasta 10 pisos. Una de las últimas oportunidades de terreno frente al mar en Mar del Plata. Escritura limpia, habilitación inmediata para proyecto.`,
    highlights: ["Frente al mar", "800 m² escriturado", "Zoning alta densidad", "Único en la zona"],
    amenities: [],
    photos: [
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&q=85",
    ],
    agent: { name: "Marcela Torres", phone: "+54 223 600-0003", photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80" },
    lat: -38.0200, lng: -57.5280,
  },
];

export const getPropertyBySlug = (slug) =>
  mockProperties.find((p) => p.slug === slug);

export const getPropertyById = (id) =>
  mockProperties.find((p) => p.id === parseInt(id));

export const getFeatured = () =>
  mockProperties.filter((p) => p.featured && p.status !== "vendido");

export const filterProperties = ({ operation, type, minPrice, maxPrice, neighborhood } = {}) => {
  return mockProperties.filter((p) => {
    if (operation && p.operation !== operation) return false;
    if (type && p.type !== type) return false;
    if (neighborhood && p.neighborhood !== neighborhood) return false;
    if (minPrice && p.price < minPrice) return false;
    if (maxPrice && p.price > maxPrice) return false;
    return true;
  });
};
